### ISSUE TITLE
A few issues to report on

### ISSUE THREAD

**Issue by OneEyedTiamat** [coco875/CharMaker#4]
[](https://user-images.githubusercontent.com/101601705/158262229-c5c85ffa-bc8a-4407-a4c0-5edf105eb6ea.png)Hey!
I came here from RPG Maker News and I have a few issues to report. First, when using the CharMaker, clicking on Face does nothing and clicking on Battler leads to this screen:
![Battler](https://user-images.githubusercontent.com/101602273/158263789-fca2dcd0-4eb6-4172-ab33-15283cce965f.png)
And it's impossible to go back to the CharMaker or anything else after clicking on Battler.

I also have a couple issues with the saved character. When I try to use the menu by using Esc, the character disappears. And when I save the character, it only changes the sprite, not the face (as it appears in the menu) or the battler (as it appears in battles).

Anyway, thanks for making this plugin, and I look forward to seeing it evolve!

**Comment by coco875** [comment]
ok I really need to add in readme then the plugin is in devellopement and is not finish with a couple of issue like this. so in Face and Battler is normally because I don't make now all the feature I make for the character. before I want also fix the ui to look like better so when the ui is end or close of the end I make for Face and Battler because is like a copy and past

**Comment by OneEyedTiamat** [comment]
Oh okay. Thanks for replying!

**Comment by coco875** [comment]
I fix this bug later and I add more information in readme

**Comment by coco875** [comment]
is fix the bug with the ui
